<!Doctype html>
<?php require_once("includes/temp_session.php");?>
<?php require_once("includes/connection.php");?>
<?php require_once("includes/functions.php");?>
<?php require_once("Classes/PHPExcel.php");?>
<?php confirm_c_logged_in();?>
<?php include("includes/header1.php"); ?>
<section class="middle">
	<?php include("includes/company_menu.php"); ?>
	<section class="center">
				<hgroup><h2 class="welcome"><center>Eligible Students</center></h2></hgroup>
				
					<?php 	
						// $rowCount=1;
						// $objPHPExcel->getProperties()->setCreator("Prabhu")
									// ->setLastModifiedBy("Gopal")
									// ->setTitle("Eligible students")
									// ->setSubject("Office 2007 XLSX Test Document")
									// ->setDescription("Test doc for Office 2007 XLSX, generated by PHPExcel.")
									// ->setKeywords("office 2007 openxml php")
									// ->setCategory("Test result file");
						//$objPHPExcel->getActiveSheet()->setTitle('trying witout knowledge');
						$year=$_POST['year']; 
						$course=$_POST['course'];
						//echo"<script type='text/javascript'>alert({$course[0]});</script>";
						$branch=implode("','",$course);
						$cgpa=$_POST['cgpa'];
						$tenth;
						$twelth;
						if(isset($_POST['10th']))
						{
							$tenth=$_POST['10th'];
						}
						if(isset($_POST['12th']))
						{
							$twelth=$_POST['12th'];
						}
						if(empty($year) || empty($branch) || empty($cgpa))
						{
							redirect_to("eligible.php");
						}
						
						$query = "SELECT `Firstname`,`Lastname`,`Branch`,`Gender`,`Mobileno`,
									FROM `student_details` WHERE Branch IN ('$branch') and `Year`='$year' and Tenthresult > '$tenth' and 
									Twelthresult > '$twelth' and (CGPA > '$cgpa' || CGPA = '$cgpa')";
							
					
						$result = mysql_query($query);
						confirm_query($result);
						
						$objPHPExcel = new PHPExcel();
						$objPHPExcel->setActiveSheetIndex(0); 
						$rowCount = 1; 
							
							// $objPHPExcel->getActiveSheet()->SetCellValue('A'.$rowCount,'Firstname');
							// $objPHPExcel->getActiveSheet()->SetCellValue('B'.$rowCount,'Lastname');
							// $objPHPExcel->getActiveSheet()->SetCellValue('C'.$rowCount,'Branch');
							// $objPHPExcel->getActiveSheet()->SetCellValue('D'.$rowCount,'Gender');
							// $objPHPExcel->getActiveSheet()->SetCellValue('E'.$rowCount,'Mobileno');
							// $objPHPExcel->getActiveSheet()->SetCellValue('F'.$rowCount,'Email');
							
						echo "</br></br></br>";
						if(mysql_num_rows($result)==0)
						{
							echo "<center><h3>No eligible students!</h3></center>";
						}
						else
						{
							echo "<center><table border=2 cellpadding=\"6\">";
							echo "<tr>
								<th>Firstname</th>
								<th>Lastname</th>
								<th>Branch</th>
								<th>Gender</th>
								<th>Mobileno</th>
								
								</tr>";
							while($result_set = mysql_fetch_array($result))
							{
								// $rowCount++;
								// $objPHPExcel->getActiveSheet()->SetCellValue('A'.$rowCount, $result_set['0']);
								// $objPHPExcel->getActiveSheet()->SetCellValue('B'.$rowCount, $result_set['1']);
								// $objPHPExcel->getActiveSheet()->SetCellValue('C'.$rowCount, $result_set['2']);
								// $objPHPExcel->getActiveSheet()->SetCellValue('D'.$rowCount, $result_set['3']);
								// $objPHPExcel->getActiveSheet()->SetCellValue('E'.$rowCount, $result_set['4']);
								// $objPHPExcel->getActiveSheet()->SetCellValue('F'.$rowCount, $result_set['5']);
								echo "
								<tr>
								<td>$result_set[0]</td>
								<td>$result_set[1]</td>
								<td>$result_set[2]</td>
								<td>$result_set[3]</td>
								<td>$result_set[4]</td>
								
								</tr>
								";
							}
							echo "</table></center>";
								
						//$objWriter = new PHPExcel_Writer_Excel2007($objPHPExcel); 
						//$objWriter->save('some_excel_file.xlsx'); 
					//header('Content-Type: application/vnd.ms-excel');
					//header('Content-Disposition: attachment;filename="01simple.xls"');
					//header('Cache-Control: max-age=0');
	 
						//$objWriter = PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel5');
						//$objWriter->save('php://output');
						
						//						exit;
						 //$objWriter = new PHPExcel_Writer_Excel2007($objPHPExcel); 	
						// $objWriter->save('results.xlsx'); 
						//$objWriter->save('php://output');
						
				?>
						</br></br></br></br>
						<form action="excel.php" method="post">
						<center><input type="submit" value="Download"/></center>
						</form>
			<?php }?>
	</section>
<?php include("includes/footer1.php");?>